---
web:
  hosts:
    "backend1":
      ansible_ssh_host: 192.168.100.103
      db_host: 192.168.100.105
    "backend2":
      ansible_ssh_host: 192.168.100.104
      db_host: 192.168.100.106
  vars:
    db_name: 'wordpress'
    db_user: 'user_wp'
    db_pass: 'password'

db:
  hosts:
    "db1":
      ansible_ssh_host: 192.168.100.105
      percona_cluster:
        name: 'wp_db-cluster'
        enabled: true
        role: master
        bootstrapper: true
        server_id: '1'
        ip_address: 192.168.100.105
    "db2":
      ansible_ssh_host: 192.168.100.106
      percona_cluster:
        name: 'wp_db-cluster'
        enabled: true
        role: master
        bootstrapper: false
        server_id: '2'
        ip_address: 192.168.100.106
  vars:
    percona_databases:
    - 'wordpress'
    percona_users:
    - name: 'user_wp'
      password: 'password'
      privs: '*.*:ALL,GRANT'
      state: present
      encrypted: no
      host: localhost