resource "local_file" "hosts" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [test]
    test ansible_host=${yandex_compute_instance.test.network_interface.0.nat_ip_address}

    DOC
  filename = "hosts"

  depends_on = [
    yandex_compute_instance.test,
  ]
}
