- hosts: web
  roles:
    - role: gfs2-role
      vars:
        gfs2_cluster_name: MyCluster
        gfs2_resource_name_lvmlockd: lvm_locking
        gfs2_resource_name_dlm: dlm_control
        gfs2_group_name_locking: locking
        gfs2_file_systems:
          - name: fs1
            resource_name_fs: gfs2-1
            pvs:
              - /dev/sdb
            vg: vg_gfs2_1
            lv: lv_gfs2_1
            lv_size: 10G
            resource_name_lv: shared-lv-1
            journals: 2
            mount_point: /var/www/html
            mount_options:
              - noatime
            state: enabled