- name: Balancing
  vars:
  tasks:

  - name: Install Nginx
    include_playbook: install_nginx.yml

  - name: Install Keepalived 
    include_playbook: install_keepalived.yml

  - name: Install DB
    include_playbook: install_db.yml

  - name: Install GFS2
    include_playbook: gfs.yml

  - name: Install Wordpress
    include_playbook: install_wordpress.yml