---
proxy:
  hosts:
    "proxy1":
      ansible_ssh_host: 192.168.100.10
      keepalived_priority: 100
    "proxy2":
      ansible_ssh_host: 192.168.100.20
      keepalived_priority: 50
  vars:
    patroni_node_name1: cluster_pgsql_01
    patroni_node_name2: cluster_pgsql_02
    patroni_node_name3: cluster_pgsql_03
db:
  hosts:
    "db1":
      ansible_ssh_host: 192.168.100.105
      patroni_node_name: cluster_pgsql_01
    "db2":
      ansible_ssh_host: 192.168.100.106
      patroni_node_name: cluster_pgsql_02
    "db3":
      ansible_ssh_host: 192.168.100.107
      patroni_node_name: cluster_pgsql_03
  vars:
    patroni_scope: 'cluster-pgsql'
    patroni_rest_password: 'password'
    patroni_postgres_password: 'password'
    patroni_replicator_password: 'password'
    cluster_virtual_ip: 192.168.100.254