---
- name: Install HA Proxy
  hosts: proxy 
  become: true
  become_method: sudo
  become_user: root
  tasks:

  - name: Install haproxy
    yum: 
      name: 'haproxy' 
      state: latest

  - name: put config
    template: 
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      backup: yes

  - name: restart and enable
    service: 
      name: haproxy
      state: restarted
      enabled: yes