---
- name: Install Patroni
  hosts: db 
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: checkout patroni
    git: 
      repo: https://github.com/zalando/patroni.git 
      dest: /opt/patroni

  - name: create /etc/patroni
    file: 
      state: directory
      dest: /etc/patroni

  - name: put postgres.yml
    template: 
      src: postgres0.yml
      dest: /etc/patroni/postgres.yml
      backup: yes

  - name: install python packages
    pip: name={{ item }}
    with_items:
      - python-etcd
      - python-consul
      - dnspython
      - boto
      - mock
      - requests
      - six
      - kazoo
      - click
      - tzlocal
      - prettytable
      - PyYAML

  - name: put patroni.service systemd unit
    template: 
      src: patroni.service
      dest: /etc/systemd/system/patroni.service
      backup: yes

  - name: Reload daemon definitions
    command: /usr/bin/systemctl daemon-reload

  - name: restart
    service: 
      name: patroni
      state: restarted
      enabled: yes