# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.network :forwarded_port, guest: 2181, host: 2181
  config.vm.provision :ansible do |ansible|
    ansible.tags = "deploy"
    ansible.playbook = "install.yml"
  end
end
